### ISSUE TITLE
"Transmit JSON data locally" does not echo local OSC data

### ISSUE THREAD

**Issue by djiamnot** [michaelpalumbo/wspd#11]
Not sure if it's a bug or a feature (or a potential feature) but selecting the option `Transmit JSON data locally? ` does not echo local OSC messages to the websocket. Such functionality would be useful for both testing and using local websockets without intervention of third parties.

**Comment by michaelpalumbo** [comment]
@djiamnot I can add this in, I can definitely see how it would be useful.

**Comment by michaelpalumbo** [comment]
@djiamnot Published in version 0.0.73. It is now set to default behaviour.
