### ISSUE TITLE
Feture request: load a configuration from CLI

### ISSUE THREAD

**Issue by djiamnot** [michaelpalumbo/wspd#12]
Currently `allhands` always starts in an interactive mode where the user will answer a series of questions to assist configuration. The recent addition of saving a named configuration and recalling it interactively is very useful and saves interaction time. However, having the ability to start `allhands` unassisted by specifying either a path to a configuration file or a name of the configuration would make it usable in deployment/launchin scripts. It would also make sense for those who like to edit JSON files by hand :wink: 
i.e.
`allhands -c ~/.local/config/allhands/test_config.json` to read a saved configuration from an arbitrary path
or
`allhands -c test_config` to run a named configuration from the default path
or some combination of those.

**Comment by michaelpalumbo** [comment]
@djiamnot nice. I'll get started on this today.

**Comment by michaelpalumbo** [comment]
@djiamnot Added in version 0.0.72, which is now published in npmjs.org. To use, see: https://github.com/michaelpalumbo/allhands/wiki/Run-with-config-file
