### ISSUE TITLE
observations while installing

### ISSUE THREAD

**Issue by DocSunset** [michaelpalumbo/wspd#17]
In the readme it says to run `npm -g allhands` to install, but this lead to a permission error. Running with sudo (`sudo npm -g allhands`) was successful.

npm also warned me about "7 high severity vulnerabilities" and advised running `npm audit fix --force`, which is a bit disconcerting for me as a newbie node user.

Looking forward to experimenting more with allhands!

**Comment by michaelpalumbo** [comment]
thanks @DocSunset ! regarding the permission error with global packages, using sudo is generally advised against. there's a [tutorial](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) in the readme which provides a means of installing global packages if you run into this. 

I'll take a look at the vulnerabilities now, thanks!

**Comment by DocSunset** [comment]
Good to know! I ran `sudo npm uninstall -h allhands`, followed the tutorial you linked to change my npm global prefix, and reinstalled without sudo successfully. I guess I missed the "If you get an error when installing related to permissions", perhaps because the block quote formatting has less contrast and appears as an aside (i.e. less important) than the main text. In any case: my bad.

Thanks again for your help!

**Comment by michaelpalumbo** [comment]
Hey Travis! I know we talked following this but I realize I forgot to reply here and thank you for your feedback :)
